### ISSUE TITLE
Crash on processing

### ISSUE THREAD

**Issue by handrake** [andrewzwicky/PUBGIS#30]
```
C:\project\PUBGIS>python -m pubgis
OpenCV Error: Insufficient memory (Failed to allocate 206451200 bytes) in cv::OutOfMemoryError, file C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp, line 55
OpenCV Error: Assertion failed (u != 0) in cv::Mat::create, file C:\projects\opencv-python\opencv\modules\core\src\matrix.cpp, line 436
Traceback (most recent call last):
  File "C:\project\PUBGIS\pubgis\gui.py", line 39, in run
    for percent, progress_minimap in match.process_match():
  File "C:\project\PUBGIS\pubgis\match.py", line 245, in process_match
    match, coords, _, _ = self.find_map_section(minimap)
  File "C:\project\PUBGIS\pubgis\match.py", line 142, in find_map_section
    cv2.TM_CCOEFF_NORMED)
cv2.error: C:\projects\opencv-python\opencv\modules\core\src\matrix.cpp:436: error: (-215) u != 0 in function cv::Mat::create
```

After some searching, it was introduced in e4c9303

This happened when I tried to process the file of size 1.5GB.

**Comment by andrewzwicky** [comment]
If you try that same file with the latest version are you still getting the crash?  I didn't do anything specific to address it, but want to see if it's still present.

**Comment by handrake** [comment]
Now it's magically gone. I even tried > 10GB file, but it went through quite smoothly. Nice!
